-- SELECT * FROM shopapp.products;
-- Where - Filtrelme Operatörleri
-- between : Belli bir aralıkta olduğunda operatörün değerleri seçer 
-- IN :  Bir ve birden çok değer belirlemenizi sağlar
-- LIKE : % ile belirtilen değerleri sorgular

-- select * from shopapp.products where Price between 2000 and 4000
-- select * from shopapp.products where ıd between 1 and 3
-- select * from shopapp.products where ıd not between 2 and 3
-- select * from shopapp.products where Category IN ('Bilgisayar')
-- select * from shopapp.products where Category IN ('Telefon','Bilgisayar')
-- select * from shopapp.products where ıd NOT IN (1,4)
-- select * from shopapp.products where Name LIKE '%Samsung%'
-- select * from shopapp.products where Name LIKE 'Sa%'
-- select * from shopapp.products where Name NOT LIKE '%Iphone%'
-- select * from shopapp.products where Name  LIKE '%Iphone%' and Price > 4000
-- select * from shopapp.products where Name  LIKE '%Samsung%' and Description LIKE '%çift%'
