-- SELECT * FROM shopapp.products;
-- SQL Fonksiyonları - Hesaplama
-- min() max() avg() => ortalama hesaplar  sum() => toplama işlemi yapar
-- select min(price) as 'Minumun Fiyat' from shopapp.products
-- select max(price) as 'Maximun Fiyat' from shopapp.products
-- select name,price from shopapp.products order by price limit 1 
-- select name,price from shopapp.products order by price DESC limit 1 
-- select count(*) from shopapp.products
-- select count(ıd) as adet from shopapp.products
-- select avg(price) as ortalama  from shopapp.products
-- select sum(price) as toplam  from shopapp.products
-- select sum(price*stock) as toplam  from shopapp.products